kind: pipeline
name: get_credentials_from_dynamo_db

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: omerlstwist
      password: OK1wRi4Z15*2h*FXtak!ZAOc
      repo: get_code_from_dynamodb
      tags: latest

matrix:
  PYTHON_VERSION:
    - 3.6.7
