kind: pipeline
name: get_credentials_from_dynamo_db

steps:
  - name: build
    image: python:3.6.7
    pull: always
    commands:
      - pip3 install --no-index --find-links=wheeldir -r requirements.txt
      - python3 get_credentials_from_dynamo_db.py