kind: pipeline
name: get_credentials_from_dynamo_db

steps:
  - name: build
  - image: python:3.6.7
  commands:
    - pip install -r requirements.txt
    - flake8 setup.py drone tests
    - nosetests --with-coverage --cover-package drone -v

matrix:
  PYTHON_VERSION:
    - 3.6.7