kind: pipeline
name: get_credentials_from_dynamo_db


pipeline:
  build: python:3.6.7
  commands:
    - python -m unittest test_get_credntials_from_dynamo_db.py

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: omerls/get_code_from_dynamodb
      tags: latest

matrix:
  PYTHON_VERSION:
    - 3.6.7
